#!/bin/sh
ac_add_options --enable-project=js
ac_add_options --disable-application=js
ac_add_options --target=wasm32-unknown-wasi
ac_add_options --disable-stdcxx-compat
ac_add_options --enable-optimize="-O0"
ac_add_options --without-system-zlib
ac_add_options --without-intl-api
ac_add_options --disable-jit
ac_add_options --disable-shared-js
ac_add_options --disable-shared-memory
ac_add_options --disable-tests
ac_add_options --disable-clang-plugin
ac_add_options --disable-jemalloc
ac_add_options --enable-debug-symbols
ac_add_options --enable-debug
export CPPFLAGS=-D_WASI_EMULATED_SIGNAL
