#ifndef _shaderloader_h_
#define _shaderloader_h_

#if defined(PRECOMPILER_VERSION) && PRECOMPILER_VERSION != 0x100
#error Unsupported precompiler version. Update shaderloader.
#endif

struct ShaderLoaderStrings
{
	char* prepare;
	char* execute;
	char* version;
};

struct DefaultShaderLoaderStruct
{
	ShaderLoaderStrings source;
};

struct ShaderLoaderParamN {
	char* buffer;
	int length;
};

void xglShaderCompiledSource(unsigned int shader, const ShaderLoaderStrings& source);
void xglShaderCompiledParamN(int n, const ShaderLoaderParamN* param, int* vect);
void xglShaderCompiledParamN(int n, const ShaderLoaderParamN* param, float* vect);
void xglShaderCompiledParamN(int n, const ShaderLoaderParamN* param, double* vect);

#define _shaderloader_defParamN(n, paramI, paramF, paramD, ...) \
	struct ShaderLoaderParam##n { char* buffer; int length; }; \
	static inline void xglShaderCompiledParam(const ShaderLoaderParam##n& param, int* vect) {xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam(const ShaderLoaderParam##n& param, float* vect) {xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam(const ShaderLoaderParam##n& param, double* vect) {xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam paramI {int vect[n] = {__VA_ARGS__}; xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam paramF {float vect[n] = {__VA_ARGS__}; xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam paramD {double vect[n] = {__VA_ARGS__}; xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);};

#define _shaderloader_defParamNoDirN(n) \
	struct ShaderLoaderParam##n { char* buffer; int length; }; \
	static inline void xglShaderCompiledParam(const ShaderLoaderParam##n& param, int* vect) {xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam(const ShaderLoaderParam##n& param, float* vect) {xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \
	static inline void xglShaderCompiledParam(const ShaderLoaderParam##n& param, double* vect) {xglShaderCompiledParamN(n, (ShaderLoaderParamN*)&param, vect);}; \


// GENERATED BY shaderloadergen.php
_shaderloader_defParamN(1,(const ShaderLoaderParam1& param,int a0),(const ShaderLoaderParam1& param,float a0),
	(const ShaderLoaderParam1& param,double a0),a0)
_shaderloader_defParamN(2,(const ShaderLoaderParam2& param,int a0,int a1),(const ShaderLoaderParam2& param,float a0,
	float a1),(const ShaderLoaderParam2& param,double a0,double a1),a0,a1)
_shaderloader_defParamN(3,(const ShaderLoaderParam3& param,int a0,int a1,int a2),(const ShaderLoaderParam3& param,
	float a0,float a1,float a2),(const ShaderLoaderParam3& param,double a0,double a1,double a2),a0,a1,a2)
_shaderloader_defParamN(4,(const ShaderLoaderParam4& param,int a0,int a1,int a2,int a3),(const ShaderLoaderParam4& param,
	float a0,float a1,float a2,float a3),(const ShaderLoaderParam4& param,double a0,double a1,double a2,double a3),a0,a1,a2,
	a3)
_shaderloader_defParamN(5,(const ShaderLoaderParam5& param,int a0,int a1,int a2,int a3,int a4),
	(const ShaderLoaderParam5& param,float a0,float a1,float a2,float a3,float a4),(const ShaderLoaderParam5& param,
	double a0,double a1,double a2,double a3,double a4),a0,a1,a2,a3,a4)
_shaderloader_defParamN(6,(const ShaderLoaderParam6& param,int a0,int a1,int a2,int a3,int a4,int a5),
	(const ShaderLoaderParam6& param,float a0,float a1,float a2,float a3,float a4,float a5),(const ShaderLoaderParam6& param,
	double a0,double a1,double a2,double a3,double a4,double a5),a0,a1,a2,a3,a4,a5)
_shaderloader_defParamN(7,(const ShaderLoaderParam7& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6),
	(const ShaderLoaderParam7& param,float a0,float a1,float a2,float a3,float a4,float a5,float a6),
	(const ShaderLoaderParam7& param,double a0,double a1,double a2,double a3,double a4,double a5,double a6),a0,a1,a2,a3,a4,
	a5,a6)
_shaderloader_defParamN(8,(const ShaderLoaderParam8& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7),
	(const ShaderLoaderParam8& param,float a0,float a1,float a2,float a3,float a4,float a5,float a6,float a7),
	(const ShaderLoaderParam8& param,double a0,double a1,double a2,double a3,double a4,double a5,double a6,double a7),a0,a1,
	a2,a3,a4,a5,a6,a7)
_shaderloader_defParamN(9,(const ShaderLoaderParam9& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8),(const ShaderLoaderParam9& param,float a0,float a1,float a2,float a3,float a4,float a5,float a6,float a7,
	float a8),(const ShaderLoaderParam9& param,double a0,double a1,double a2,double a3,double a4,double a5,double a6,
	double a7,double a8),a0,a1,a2,a3,a4,a5,a6,a7,a8)
_shaderloader_defParamN(10,(const ShaderLoaderParam10& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9),(const ShaderLoaderParam10& param,float a0,float a1,float a2,float a3,float a4,float a5,float a6,float a7,
	float a8,float a9),(const ShaderLoaderParam10& param,double a0,double a1,double a2,double a3,double a4,double a5,
	double a6,double a7,double a8,double a9),a0,a1,a2,a3,a4,a5,a6,a7,a8,a9)
_shaderloader_defParamN(11,(const ShaderLoaderParam11& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9,int a10),(const ShaderLoaderParam11& param,float a0,float a1,float a2,float a3,float a4,float a5,float a6,
	float a7,float a8,float a9,float a10),(const ShaderLoaderParam11& param,double a0,double a1,double a2,double a3,
	double a4,double a5,double a6,double a7,double a8,double a9,double a10),a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10)
_shaderloader_defParamN(12,(const ShaderLoaderParam12& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9,int a10,int a11),(const ShaderLoaderParam12& param,float a0,float a1,float a2,float a3,float a4,float a5,
	float a6,float a7,float a8,float a9,float a10,float a11),(const ShaderLoaderParam12& param,double a0,double a1,double a2,
	double a3,double a4,double a5,double a6,double a7,double a8,double a9,double a10,double a11),a0,a1,a2,a3,a4,a5,a6,a7,a8,
	a9,a10,a11)
_shaderloader_defParamN(13,(const ShaderLoaderParam13& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9,int a10,int a11,int a12),(const ShaderLoaderParam13& param,float a0,float a1,float a2,float a3,float a4,
	float a5,float a6,float a7,float a8,float a9,float a10,float a11,float a12),(const ShaderLoaderParam13& param,double a0,
	double a1,double a2,double a3,double a4,double a5,double a6,double a7,double a8,double a9,double a10,double a11,
	double a12),a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12)
_shaderloader_defParamN(14,(const ShaderLoaderParam14& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9,int a10,int a11,int a12,int a13),(const ShaderLoaderParam14& param,float a0,float a1,float a2,float a3,
	float a4,float a5,float a6,float a7,float a8,float a9,float a10,float a11,float a12,float a13),
	(const ShaderLoaderParam14& param,double a0,double a1,double a2,double a3,double a4,double a5,double a6,double a7,
	double a8,double a9,double a10,double a11,double a12,double a13),a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13)
_shaderloader_defParamN(15,(const ShaderLoaderParam15& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9,int a10,int a11,int a12,int a13,int a14),(const ShaderLoaderParam15& param,float a0,float a1,float a2,
	float a3,float a4,float a5,float a6,float a7,float a8,float a9,float a10,float a11,float a12,float a13,float a14),
	(const ShaderLoaderParam15& param,double a0,double a1,double a2,double a3,double a4,double a5,double a6,double a7,
	double a8,double a9,double a10,double a11,double a12,double a13,double a14),a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,
	a13,a14)
_shaderloader_defParamN(16,(const ShaderLoaderParam16& param,int a0,int a1,int a2,int a3,int a4,int a5,int a6,int a7,
	int a8,int a9,int a10,int a11,int a12,int a13,int a14,int a15),(const ShaderLoaderParam16& param,float a0,float a1,
	float a2,float a3,float a4,float a5,float a6,float a7,float a8,float a9,float a10,float a11,float a12,float a13,
	float a14,float a15),(const ShaderLoaderParam16& param,double a0,double a1,double a2,double a3,double a4,double a5,
	double a6,double a7,double a8,double a9,double a10,double a11,double a12,double a13,double a14,double a15),a0,a1,a2,a3,
	a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15)
_shaderloader_defParamNoDirN(17)
_shaderloader_defParamNoDirN(18)
_shaderloader_defParamNoDirN(19)
_shaderloader_defParamNoDirN(20)
_shaderloader_defParamNoDirN(21)
_shaderloader_defParamNoDirN(22)
_shaderloader_defParamNoDirN(23)
_shaderloader_defParamNoDirN(24)
_shaderloader_defParamNoDirN(25)
_shaderloader_defParamNoDirN(26)
_shaderloader_defParamNoDirN(27)
_shaderloader_defParamNoDirN(28)
_shaderloader_defParamNoDirN(29)
_shaderloader_defParamNoDirN(30)
_shaderloader_defParamNoDirN(31)
_shaderloader_defParamNoDirN(32)
_shaderloader_defParamNoDirN(33)
_shaderloader_defParamNoDirN(34)
_shaderloader_defParamNoDirN(35)
_shaderloader_defParamNoDirN(36)
_shaderloader_defParamNoDirN(37)
_shaderloader_defParamNoDirN(38)
_shaderloader_defParamNoDirN(39)
_shaderloader_defParamNoDirN(40)
_shaderloader_defParamNoDirN(41)
_shaderloader_defParamNoDirN(42)
_shaderloader_defParamNoDirN(43)
_shaderloader_defParamNoDirN(44)
_shaderloader_defParamNoDirN(45)
_shaderloader_defParamNoDirN(46)
_shaderloader_defParamNoDirN(47)
_shaderloader_defParamNoDirN(48)
_shaderloader_defParamNoDirN(49)
_shaderloader_defParamNoDirN(50)
_shaderloader_defParamNoDirN(51)
_shaderloader_defParamNoDirN(52)
_shaderloader_defParamNoDirN(53)
_shaderloader_defParamNoDirN(54)
_shaderloader_defParamNoDirN(55)
_shaderloader_defParamNoDirN(56)
_shaderloader_defParamNoDirN(57)
_shaderloader_defParamNoDirN(58)
_shaderloader_defParamNoDirN(59)
_shaderloader_defParamNoDirN(60)
_shaderloader_defParamNoDirN(61)
_shaderloader_defParamNoDirN(62)
_shaderloader_defParamNoDirN(63)
_shaderloader_defParamNoDirN(64)

#endif
