
#ifndef FLOOD_FILL_MAP_H
#define FLOOD_FILL_MAP_H

#include <stdint.h>

struct FloodFillMapEntry {
    uint8_t count;
    struct {
        int8_t dx;
        int8_t dy;
    } jumps[4];
};

static FloodFillMapEntry floodFillMap[256] = {
    { .count = 0, .jumps = {  } },
    { .count = 1, .jumps = { {1, 1} } },
    { .count = 1, .jumps = { {0, 1} } },
    { .count = 1, .jumps = { {0, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {1, 0} } },
    { .count = 1, .jumps = { {1, 0} } },
    { .count = 1, .jumps = { {0, 1} } },
    { .count = 1, .jumps = { {0, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, 0} } },
    { .count = 2, .jumps = { {-1, 1}, {1, 0} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {1, -1} } },
    { .count = 2, .jumps = { {1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {0, 1}, {1, -1} } },
    { .count = 2, .jumps = { {0, 1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, 1}, {1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, -1} } },
    { .count = 1, .jumps = { {1, -1} } },
    { .count = 1, .jumps = { {1, -1} } },
    { .count = 1, .jumps = { {0, 1} } },
    { .count = 1, .jumps = { {0, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {1, -1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 3, .jumps = { {-1, 0}, {1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 3, .jumps = { {-1, 0}, {1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 2, .jumps = { {-1, 0}, {1, -1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 2, .jumps = { {0, -1}, {1, 1} } },
    { .count = 2, .jumps = { {0, -1}, {0, 1} } },
    { .count = 2, .jumps = { {0, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 3, .jumps = { {-1, 1}, {0, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 2, .jumps = { {0, -1}, {1, 1} } },
    { .count = 2, .jumps = { {0, -1}, {0, 1} } },
    { .count = 2, .jumps = { {0, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 3, .jumps = { {-1, 1}, {0, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 1, .jumps = { {0, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 2, .jumps = { {-1, 1}, {0, -1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 2, .jumps = { {-1, 0}, {1, 1} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, 0} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 0} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 0} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, 0} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, 0} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 0} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 0} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 0} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 0} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {1, -1}, {1, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {0, 1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {0, 1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, -1} } },
    { .count = 4, .jumps = { {-1, -1}, {-1, 1}, {1, -1}, {1, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 3, .jumps = { {-1, -1}, {1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {0, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 3, .jumps = { {-1, -1}, {-1, 1}, {1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 2, .jumps = { {-1, -1}, {-1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 2, .jumps = { {-1, -1}, {1, 1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
    { .count = 1, .jumps = { {-1, -1} } },
};
#endif // FLOOD_FILL_MAP_H
